# Generated by Django 4.2.1 on 2023-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='content'),
        ),
    ]
